### ISSUE TITLE
Non-zero scale start?

### ISSUE THREAD

**Issue by jazztunes** [Bodmer/TFT_eWidget#10]
It's not clear what the analogMeter's "fullScale" parameter should be when the scale doesn't start at zero. Same trouble when the scale start is negative. Is this a bug, or is there something I'm missing?

Trying to display 3.5 on a scale of 2 through 6 and it read something like 4.4 instead.

```
#include <TFT_eSPI.h>     // Hardware-specific library
#include <TFT_eWidget.h>  // Widget library

TFT_eSPI tft  = TFT_eSPI();      // Invoke custom library

MeterWidget   mw  = MeterWidget(&tft);

void setup(void) 
{
  tft.init();
  tft.setRotation(3);
  
  mw.analogMeter(0, 0, 6.0, "Val", "2", "3", "4", "5", "6");    // Draw analogue meter at 0, 0

  mw.updateNeedle(3.5, 0);
}

void loop() 
{
  delay(1000);
}
```

**Comment by Bodmer** [comment]
I have updated the library to allow a non zero start. New functions has an extra parameter (startScale):
```
    void analogMeter(uint16_t x, uint16_t y, float startScale, float endScale, const char *units, const char *s0, const char *s1, const char *s2, const char *s3, const char *s4);
```
Example for a meter from 1.0 to 2.0:
```
amps.analogMeter(0, 0, 1.0, 2.0, "mA", "1.0", "1.25", "1.5", "1.75", "2.0");    // Draw analogue meter at 0, 0
```

**Comment by jazztunes** [comment]
This is great! I don't see 0.0.6 yet in the Arduino Library Manager, so I'm going to pull down your changes manually for now - thanks for the quick attention!
