### ISSUE TITLE
Point On Graph 

### ISSUE THREAD

**Issue by Sudupatil** [Bodmer/TFT_eWidget#5]
[Book1.xlsx](https://github.com/Bodmer/TFT_eWidget/files/9483824/Book1.xlsx)
![IMG_20220904_092925](https://user-images.githubusercontent.com/99311112/188296978-b81d1d98-8fb7-4db1-a1a6-21b41196110d.jpg)
![Capture](https://user-images.githubusercontent.com/99311112/188296988-08a6bcf3-34e4-4862-b44a-6e4cd2630326.JPG)
[Graph_demo_2.txt](https://github.com/Bodmer/TFT_eWidget/files/9483828/Graph_demo_2.txt)

Hello,

Your library helps me lot, recently I was working with TFT_eWidget and I had notice point plotting are not exact, perhaps I am not setting things properly. you can find the code I am using in Graph_demo_2.txt. reference graph values you can see in either Capture.jpg or in excel file.

Please let me know what I had done wrong.

Thanks and regards
Sudarshan Patil

**Comment by Bodmer** [comment]
Hi,
The graph is specified to have a range of -15 to 50, but the y axis has then be labeled every 6 graph units to be 0 to 40. This means the drawn y axis numbers are in the wrong position. It should be labelled every 5 graph units in this case.

Points and grids should be added in graph units, so for the y axis a label every 5 units. This is then scaled to the display graphs area for you. Similarly you can specif the x range as 0.0 to 12.0 then add number labels every 1.0 units.

Part of the graph is also off screen as it is specified as 350 pixels high. The screen size is 320 high.

Here is a corrected version with the graph x scaled from 0.0 to 12.0 and y scaled from 0.0 to 40.0:

[Widget_issue_5.zip](https://github.com/Bodmer/TFT_eWidget/files/9485445/Widget_issue_5.zip)

**Comment by Sudupatil** [comment]
Hi,

Thank you for your quick reply,  I tried a lot of things but I couldn't understand. This is now working perfectly.  thank you very much.
![IMG_20220905_091143](https://user-images.githubusercontent.com/99311112/188356899-dbe6a40f-9268-4239-a01b-7666405a9d5b.jpg)
