### ISSUE TITLE
slider demo touch not working properly

### ISSUE THREAD

**Issue by ashoksharma842** [Bodmer/TFT_eWidget#6]
I tried the button widget and it works fine.
That indicates that the setup is correct.
Then I tried the slider widget it shows correct in display,
but the touch doesn't work properly.
touching the top side moves the right side slider!
It seems like the coordinates are improper.

**Comment by ashoksharma842** [comment]
Yep, it worked!
I tried the calibration sketch, it didn't work.
But calibrating with the sketch itself, it works fine!
Even if I calibrate using button widget, I have to calibrate again for slider widget.
Button widget calibration won't work with slider widget!

**Comment by Bodmer** [comment]
Glad to hear it is working, thanks for letting me know.
